import type { Crop, Livestock, FarmInput, Transaction, MarketPrice, Buyer } from "@/types"

export const demoCrops: Crop[] = [
  {
    id: "1",
    user_id: "1",
    name: "Maize",
    variety: "ZM 523",
    area: 2.5,
    planting_date: "2024-09-15",
    expected_harvest_date: "2025-01-15",
    status: "growing",
    notes: "Using organic fertilizer",
    created_at: "2024-09-15T10:00:00Z",
  },
  {
    id: "2",
    user_id: "1",
    name: "Beans",
    variety: "Red Kidney",
    area: 1.0,
    planting_date: "2024-10-01",
    expected_harvest_date: "2025-01-01",
    status: "growing",
    created_at: "2024-10-01T10:00:00Z",
  },
  {
    id: "3",
    user_id: "1",
    name: "Tomatoes",
    variety: "Roma",
    area: 0.5,
    planting_date: "2024-08-01",
    expected_harvest_date: "2024-11-01",
    actual_harvest_date: "2024-11-05",
    status: "harvested",
    yield_amount: 800,
    yield_unit: "kg",
    created_at: "2024-08-01T10:00:00Z",
  },
]

export const demoLivestock: Livestock[] = [
  {
    id: "1",
    user_id: "1",
    type: "Cattle",
    breed: "Friesian",
    count: 3,
    acquisition_date: "2023-06-15",
    purpose: "Milk Production",
    health_status: "healthy",
    created_at: "2023-06-15T10:00:00Z",
  },
  {
    id: "2",
    user_id: "1",
    type: "Goats",
    breed: "Alpine",
    count: 8,
    acquisition_date: "2024-01-10",
    purpose: "Meat Production",
    health_status: "vaccinated",
    notes: "Recently vaccinated against PPR",
    created_at: "2024-01-10T10:00:00Z",
  },
  {
    id: "3",
    user_id: "1",
    type: "Chickens",
    breed: "Kuroiler",
    count: 50,
    acquisition_date: "2024-03-20",
    purpose: "Egg Production",
    health_status: "healthy",
    created_at: "2024-03-20T10:00:00Z",
  },
]

export const demoInputs: FarmInput[] = [
  {
    id: "1",
    user_id: "1",
    type: "fertilizer",
    name: "NPK 17-17-17",
    quantity: 50,
    unit: "kg",
    cost: 75000,
    application_date: "2024-10-15",
    applied_to: "Maize",
    created_at: "2024-10-15T10:00:00Z",
  },
  {
    id: "2",
    user_id: "1",
    type: "pesticide",
    name: "Cypermethrin",
    quantity: 2,
    unit: "liters",
    cost: 18000,
    application_date: "2024-11-01",
    applied_to: "Beans",
    notes: "Applied during early morning",
    created_at: "2024-11-01T10:00:00Z",
  },
]

export const demoTransactions: Transaction[] = [
  {
    id: "1",
    user_id: "1",
    type: "income",
    category: "Crop Sales",
    amount: 450000,
    description: "Tomato harvest sale to local market",
    date: "2024-11-10",
    payment_method: "Mobile Money",
    created_at: "2024-11-10T10:00:00Z",
  },
  {
    id: "2",
    user_id: "1",
    type: "income",
    category: "Milk Sales",
    amount: 180000,
    description: "Monthly milk sales",
    date: "2024-11-01",
    payment_method: "Cash",
    created_at: "2024-11-01T10:00:00Z",
  },
  {
    id: "3",
    user_id: "1",
    type: "expense",
    category: "Fertilizers",
    amount: 75000,
    description: "NPK 17-17-17 for maize",
    date: "2024-10-15",
    payment_method: "Mobile Money",
    created_at: "2024-10-15T10:00:00Z",
  },
  {
    id: "4",
    user_id: "1",
    type: "expense",
    category: "Seeds & Planting",
    amount: 45000,
    description: "Maize seeds",
    date: "2024-09-10",
    payment_method: "Cash",
    created_at: "2024-09-10T10:00:00Z",
  },
  {
    id: "5",
    user_id: "1",
    type: "income",
    category: "Egg Sales",
    amount: 120000,
    description: "Weekly egg sales",
    date: "2024-10-28",
    payment_method: "Mobile Money",
    created_at: "2024-10-28T10:00:00Z",
  },
  {
    id: "6",
    user_id: "1",
    type: "expense",
    category: "Animal Feed",
    amount: 90000,
    description: "Chicken feed",
    date: "2024-10-20",
    payment_method: "Cash",
    created_at: "2024-10-20T10:00:00Z",
  },
  {
    id: "7",
    user_id: "1",
    type: "expense",
    category: "Labor Costs",
    amount: 60000,
    description: "Harvest labor",
    date: "2024-11-05",
    payment_method: "Cash",
    created_at: "2024-11-05T10:00:00Z",
  },
]

export const demoMarketPrices: MarketPrice[] = [
  {
    id: "1",
    product: "Maize",
    category: "Grains",
    price_per_unit: 450,
    unit: "kg",
    market_location: "Kimironko Market",
    district: "Gasabo",
    province: "Kigali City",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "up",
  },
  {
    id: "2",
    product: "Beans",
    category: "Legumes",
    price_per_unit: 850,
    unit: "kg",
    market_location: "Nyabugogo Market",
    district: "Nyarugenge",
    province: "Kigali City",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "stable",
  },
  {
    id: "3",
    product: "Tomatoes",
    category: "Vegetables",
    price_per_unit: 600,
    unit: "kg",
    market_location: "Kimisagara Market",
    district: "Nyarugenge",
    province: "Kigali City",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "down",
  },
  {
    id: "4",
    product: "Irish Potatoes",
    category: "Tubers",
    price_per_unit: 380,
    unit: "kg",
    market_location: "Musanze Market",
    district: "Musanze",
    province: "Northern Province",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "up",
  },
  {
    id: "5",
    product: "Sweet Potatoes",
    category: "Tubers",
    price_per_unit: 320,
    unit: "kg",
    market_location: "Huye Market",
    district: "Huye",
    province: "Southern Province",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "stable",
  },
  {
    id: "6",
    product: "Cabbage",
    category: "Vegetables",
    price_per_unit: 280,
    unit: "kg",
    market_location: "Kimironko Market",
    district: "Gasabo",
    province: "Kigali City",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "up",
  },
  {
    id: "7",
    product: "Carrots",
    category: "Vegetables",
    price_per_unit: 520,
    unit: "kg",
    market_location: "Nyabugogo Market",
    district: "Nyarugenge",
    province: "Kigali City",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "stable",
  },
  {
    id: "8",
    product: "Rice",
    category: "Grains",
    price_per_unit: 950,
    unit: "kg",
    market_location: "Rwamagana Market",
    district: "Rwamagana",
    province: "Eastern Province",
    last_updated: "2024-12-14T08:00:00Z",
    trend: "up",
  },
]

export const demoBuyers: Buyer[] = [
  {
    id: "1",
    name: "Kigali Fresh Foods Ltd",
    type: "company",
    products_buying: ["Tomatoes", "Cabbage", "Carrots", "Onions"],
    location: "Kigali City Center",
    district: "Nyarugenge",
    province: "Kigali City",
    contact_phone: "+250788456789",
    contact_email: "procurement@kigalifresh.rw",
    rating: 4.5,
    verified: true,
  },
  {
    id: "2",
    name: "Twungane Farmers Cooperative",
    type: "cooperative",
    products_buying: ["Maize", "Beans", "Rice"],
    location: "Musanze",
    district: "Musanze",
    province: "Northern Province",
    contact_phone: "+250785234567",
    rating: 4.2,
    verified: true,
  },
  {
    id: "3",
    name: "Rwanda Exports International",
    type: "export",
    products_buying: ["Coffee", "Tea", "Avocado"],
    location: "Kigali",
    district: "Gasabo",
    province: "Kigali City",
    contact_phone: "+250788123456",
    contact_email: "buyers@rwandaexports.com",
    rating: 4.8,
    verified: true,
  },
  {
    id: "4",
    name: "Huye Dairy Processors",
    type: "company",
    products_buying: ["Milk", "Eggs"],
    location: "Huye",
    district: "Huye",
    province: "Southern Province",
    contact_phone: "+250782345678",
    rating: 4.3,
    verified: true,
  },
  {
    id: "5",
    name: "Jean Paul Uwimana",
    type: "individual",
    products_buying: ["Irish Potatoes", "Sweet Potatoes", "Cassava"],
    location: "Rwamagana",
    district: "Rwamagana",
    province: "Eastern Province",
    contact_phone: "+250789876543",
    rating: 4.0,
    verified: false,
  },
  {
    id: "6",
    name: "Inyange Industries",
    type: "company",
    products_buying: ["Fruits", "Vegetables", "Milk"],
    location: "Kigali",
    district: "Kicukiro",
    province: "Kigali City",
    contact_phone: "+250788999888",
    contact_email: "sourcing@inyange.rw",
    rating: 4.7,
    verified: true,
  },
]
